# Generated by Django 3.2.4 on 2021-08-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeuserdetails',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
